version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - todo-network

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
